name: Generate Snake Graph

on:
  schedule:
    - cron: "0 0 * * *" # Roda todo dia
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Permissão para o robô escrever no repositório
    permissions:
      contents: write

    steps:
      # 1. Gera o GRÁFICO da cobra (não mais a animação solta)
      - uses: Platane/snk@v3
        with:
          github_user_name: vitorows # Seu usuário
          
          # Pede os arquivos do GRÁFICO (contribution)
          outputs: |
            dist/contribution-snake.svg
            dist/contribution-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 2. Publica os arquivos no branch 'output'
      - name: Push snake graph to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output # O branch de saída
          build_dir: dist     # A pasta que contém os arquivos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
