name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Roda uma vez por dia
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - uses: Platane/snk@v3
        with:
          # O seu nome de usuário do GitHub (está correto)
          github_user_name: vitorows
          
          # Lista de arquivos que serão gerados
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
