name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Roda todo dia
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    
    # -----------------------------------------------
    # A CORREÇÃO ESTÁ AQUI. DÁ PERMISSÃO AO ROBÔ.
    # -----------------------------------------------
    permissions:
      contents: write
    # -----------------------------------------------

    steps:
      # 1. Gera os arquivos da cobra
      - uses: Platane/snk@v3
        with:
          github_user_name: vitorows # Seu usuário
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 2. Publica os arquivos no branch 'output'
      - name: Push snake files to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output # O nome do novo branch
          build_dir: dist     # A pasta que contém os arquivos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
